### ISSUE TITLE
problem after run node index.js

### ISSUE THREAD

**Issue by farewellXD** [PDIS/join-archive#2]
the error messange

'Could not spawn [/home/markdai/phantomjs/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.'

Could you tell me how to fix this ?

many thx

**Comment by mark19891107** [comment]
抱歉，已經修正了

是因為 node_modules 資料夾，當初可能沒上傳好，請刪掉 node_modules 資料夾，再重新 npm install

或是你可以重新 clone ，再依照 README.md 的步驟執行就可以了

感謝
